name: example
description: A new Flutter project.
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  tinkoff_acquiring:
    path: ../

flutter:
  uses-material-design: true