name: tinkoff_acquiring

packages:
  - packages/**
  - example/*

ide:
  intellij:
    true
  vscode:
    true

scripts:
  format:code: >
    melos exec -c 6 -- \
      dartfmt -w .

  format:import: >
    melos exec -c 6 -- \
      pub global run import_sorter:main lib\/* --no-comments

  # Run `dart analyze` in all packages.
  # Note: you can also rely on your IDEs Dart Analysis / Issues window.
  analyze:
    run: |
      melos exec -c 1 --no-private --ignore="*example*" -- \
        dart analyze . --fatal-infos

  lint:pub: >
    melos exec -c 1 --fail-fast --no-private --ignore="*example*" -- \
      pub publish --dry-run

  lint:pana: >
    melos exec -c 1 --fail-fast --no-private --ignore="*example*" -- \
      pana

  # Additional cleanup lifecycle script, executed when `melos clean` is ran.
  postclean: >
    melos exec -c 1 -- "flutter clean"