name: tinkoff_acquiring
description: Flutter Tinkoff Acquiring SDK is a simple way to integrate payments into your mobile application.
version: 2.1.0
repository: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter
issue_tracker: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  comparer: ^2.0.1
  crypto: ^3.0.0
  crypton: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  webview_flutter: ^2.0.2

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.2