name: tinkoff_acquiring
description: Flutter Tinkoff Acquiring SDK is a simple way to integrate payments into your mobile application.
version: 3.0.3
repository: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter
issue_tracker: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  comparer: ^2.0.1
  crypto: ^3.0.1
  crypton: ^2.0.2
  http: ^0.13.3
  json_annotation: ^4.1.0
  meta: ^1.7.0

dev_dependencies:
  test: ^1.17.10
  build_runner: ^2.0.6
  json_serializable: ^5.0.0